sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lalitmehta/docker-react -f Dockerfile.dev .

  
script:
  - docker run -e CI=true lalitmehta/docker-react npm run test -- --coverage